-- V38: Expand mate_wiki_chunk.content from TEXT (64KB) to TEXT (16MB)
-- In KingbaseES/PostgreSQL, TEXT is already unlimited (up to 1GB),
-- so this migration is a no-op. Keep for Flyway version compatibility.
