-- mate_wiki_hot_cache: KB-level rolling snapshot of "what happened recently"
-- in this knowledge base, injected into the agent system prompt so the model
-- doesn't have to wiki_search the obvious every turn.
--
-- One row per KB (uk_whc_kb). Body is markdown rendered from a four-section
-- structure (Last Updated / Key Recent Facts / Recent Changes / Active Threads),
-- regenerated by an LLM call after compile/page/conversation events; this
-- migration only provisions storage. Consumers and updater land in later PRs.

CREATE TABLE IF NOT EXISTS mate_wiki_hot_cache (
    id              BIGINT  PRIMARY KEY,
    kb_id           BIGINT      NOT NULL,

    content         TEXT,
    content_hash    CHAR(64),

    last_updated    TIMESTAMP(3),
    update_reason   VARCHAR(32),

    rebuild_count            BIGINT NOT NULL DEFAULT 0,
    last_rebuild_started_at  TIMESTAMP(3),
    last_rebuild_duration_ms BIGINT,
    last_rebuild_error       VARCHAR(512),

    create_time     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    deleted         SMALLINT     NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_whc_kb ON mate_wiki_hot_cache (kb_id, deleted);
CREATE INDEX IF NOT EXISTS idx_whc_kb ON mate_wiki_hot_cache (kb_id, deleted);
