-- mate_wiki_hot_cache: KB-level rolling snapshot of "what happened recently"
-- in this knowledge base, injected into the agent system prompt so the model
-- doesn't have to wiki_search the obvious every turn.
--
-- One row per KB (uk_whc_kb). Body is markdown rendered from a four-section
-- structure (Last Updated / Key Recent Facts / Recent Changes / Active Threads),
-- regenerated by an LLM call after compile/page/conversation events; this
-- migration only provisions storage. Consumers and updater land in later PRs.

CREATE TABLE IF NOT EXISTS mate_wiki_hot_cache (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    kb_id           BIGINT      NOT NULL,

    content         TEXT,
    content_hash    CHAR(64),

    last_updated    DATETIME(3),
    update_reason   VARCHAR(32),

    rebuild_count            BIGINT NOT NULL DEFAULT 0,
    last_rebuild_started_at  DATETIME(3),
    last_rebuild_duration_ms BIGINT,
    last_rebuild_error       VARCHAR(512),

    create_time     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted         TINYINT     NOT NULL DEFAULT 0,

    UNIQUE KEY uk_whc_kb (kb_id, deleted),
    KEY idx_whc_kb (kb_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
